# -*- coding: utf-8 -*-
"""insurancepredc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xoXxd4RaILKOjmrsmbiosegVc3MHTj0A
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score

medin = pd.read_csv('/content/Insurancepredc.csv')

medin.head()

medin.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
medin['sex']=le.fit_transform(medin['sex'])
medin['region']=le.fit_transform(medin['region'])
medin['smoker']=le.fit_transform(medin['smoker'])

X = medin[['age','sex','bmi','children','smoker','region']]
y = medin['charges']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

LR = LinearRegression()

LR.fit(X_train, y_train)

y_pred = LR.predict(X_test)
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

LR.predict([[18,1,29,4,1,0]])